# Generated by Django 3.2.5 on 2021-08-06 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
