# Generated by Django 3.2.5 on 2021-08-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_weapon_selleraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='powerPerPrice',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
