# Generated by Django 3.2.5 on 2021-08-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_weapon_powerperprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='banned',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
