# Generated by Django 3.2.5 on 2021-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_weapon_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
