# Generated by Django 3.2.5 on 2021-08-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='banned',
        ),
    ]
