# Generated by Django 3.2.5 on 2021-08-13 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_weapon_banned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weapon',
            options={'ordering': ['-powerPerPrice']},
        ),
    ]
