# Generated by Django 3.2.5 on 2021-08-19 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_fight'),
    ]

    operations = [
        migrations.AddField(
            model_name='fight',
            name='usd_cost',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fight',
            name='usd_earned',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
