# Generated by Django 3.2.5 on 2021-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20210819_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='owner',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
