# Generated by Django 3.2.5 on 2021-08-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_personalaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='xp_unclaimed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
