# Generated by Django 3.2.5 on 2021-08-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_character_xp_unclaimed'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('xp_required', models.IntegerField()),
            ],
        ),
    ]
