# Generated by Django 3.2.5 on 2021-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_xptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalaccount',
            name='bnb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='skill',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='skill_in_game',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personalaccount',
            name='skill_staked',
            field=models.FloatField(default=0),
        ),
    ]
