# Generated by Django 3.2.5 on 2021-08-22 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_auto_20210822_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('updated', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
