# Generated by Django 3.2.5 on 2021-10-12 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('market_cap', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
