# Generated by Django 3.2.5 on 2021-10-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='market_cap',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='volume',
            field=models.FloatField(),
        ),
    ]
