# Generated by Django 3.2.5 on 2021-10-12 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0002_auto_20211012_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_num', models.IntegerField()),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('volume', models.FloatField()),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='created',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='price',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='volume',
        ),
        migrations.CreateModel(
            name='Delta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_between', models.FloatField()),
                ('rank_num', models.IntegerField()),
                ('price', models.FloatField()),
                ('market_cap', models.FloatField()),
                ('volume', models.FloatField()),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto')),
                ('data1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fist_data', to='cmc.data')),
                ('data2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_data', to='cmc.data')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto'),
        ),
    ]
