# Generated by Django 3.2.5 on 2021-10-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0004_auto_20211012_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('cmc_link', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=3000)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=3000)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=3000)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.community')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmc.crypto')),
            ],
        ),
    ]
