# Generated by Django 3.2.5 on 2021-10-15 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0005_community_cryptocommunity_cryptoexchange_cryptotag_cryptowebsite_exchange_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
