# Generated by Django 3.2.5 on 2021-10-16 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0006_crypto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='link',
            field=models.CharField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
