# Generated by Django 3.2.5 on 2021-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmc', '0008_alter_tag_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoexchange',
            name='pair',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
